title: Site

fields:
  pageSettings:
    label: Page Settings
    type: headline

  title:
    label: Title
    type:  text

  author:
    label: Author
    type:  text

  description:
    label: Description
    type:  textarea
    
  copyright:
    label: Copyright
    type:  textarea

  pageFooter:
    label: Footer
    type: headline

  footerOne:
    label: Footer Spalte 1
    type: textarea
    width: 1/3

  footerTwo:
    label: Footer Spalte 2
    type: textarea
    width: 1/3

  footerThree:
    label: Footer Spalte 3
    type: textarea
    width: 1/3

  pageGoogle:
    label: Google Analytics
    type: headline
    
  google:
    label: Analytics Code
    type:  text
    
  pageFacebook:
    label: Facebook
    type: headline
    
  facebookTitel:
    label: Facebook Title
    type:  text
    
  facebookDescription:
    label: Facebook Description
    type:  text
    
  facebookImage:
    label: Facebook Image
    type: image